### ISSUE TITLE
questionable condition

### ISSUE THREAD

**Issue by Bryukh** [suwanditan/checkio-task-number-guess#1]
"From range from 1 to 100". Please, add about 100 is included.

**Comment by suwanditan** [comment]
there is no such thing for "questionable". However, I removed "range" word.

**Comment by Bryukh** [comment]
Thanks. You can just add "inclusive" word.

Valentin Bryukhanov.

18.09.2013, â 23:33, suwanditan notifications@github.com íàïèñàë(à):
